# 稳定版：永远生成合法版本号，永远不炸编译
try {
    # 尝试从 Git 获取版本信息
    $tag = git describe --always --tags "--abbrev=0" --exclude latest 2>$null
    $revision = git describe --always --tags --exclude latest 2>$null
    
    # 如果获取失败（例如没有标签），使用默认版本
    if (-not $tag -or $tag -match '^[0-9a-f]{7,}$') {
        # 如果 tag 是纯哈希值，使用默认版本
        $tag = "1.0.0"
    }
    if (-not $revision -or $revision -match '^[0-9a-f]{7,}$') {
        # 如果 revision 是纯哈希值，使用默认版本
        $revision = "1.0.0.0"
    }
} catch {
    # 发生异常时使用默认版本
    $tag = "1.0.0"
    $revision = "1.0.0.0"
}

$text = @"
// This file is generated by update-version.ps1 

using System.Reflection;

[assembly: AssemblyVersion("$tag")]
[assembly: AssemblyInformationalVersion("$revision")]
"@

$text | Out-File $PSScriptRoot\..\GitVersion.cs -Encoding utf8
