# 稳定版：永远生成合法版本号，永远不炸编译
$tag = "1.0.0"
$revision = "1.0.0.0"

$text = @"
// This file is generated by update-version.ps1 
 
using System.Reflection;
 
[assembly: AssemblyVersion("$tag")]
[assembly: AssemblyInformationalVersion("$revision")]
"@

$text | Out-File $PSScriptRoot\..\GitVersion.cs -Encoding utf8
